Repository simpleweb/open-format, pull requests merged in 2022-09, with the labels that each got.

#118 Change to href react QuickStart
  docs/docs/introduction.mdx
Labels: bug

#122 Feature: Introduction of the Showcase
  docs/docs/introduction.mdx
  docs/docusaurus.config.js
  docs/package.json
  docs/src/components/Svg/index.tsx
  docs/src/components/Svg/styles.module.css
  docs/src/components/svgIcons/FavoriteIcon/index.tsx
  docs/src/css/custom.css
  docs/src/data/showcase/Amplify.jpg
  docs/src/data/showcase/DaftSpringer.jpg
  docs/src/data/showcase/OfficeIncentiveScheme.jpg
  docs/src/data/showcase/OpenFormatNFT.jpg
  docs/src/data/showcase/SimpleFaucets.jpg
  docs/src/data/showcase/SimpleNFT.jpg
  docs/src/data/showcase/YourTub3.jpg
  docs/src/data/users.tsx
  docs/src/pages/showcase/_components/ShowcaseCard/index.tsx
  docs/src/pages/showcase/_components/ShowcaseFilterToggle/index.tsx
  docs/src/pages/showcase/_components/ShowcaseFilterToggle/styles.module.css
  docs/src/pages/showcase/_components/ShowcaseTagSelect/index.tsx
  docs/src/pages/showcase/_components/ShowcaseTagSelect/styles.module.css
  docs/src/pages/showcase/_components/ShowcaseTooltip/index.tsx
  docs/src/pages/showcase/_components/ShowcaseTooltip/styles.module.css
  docs/src/pages/showcase/index.tsx
  docs/src/pages/showcase/styles.module.css
  docs/src/utils/__tests__/jsUtils.test.ts
  docs/src/utils/jsUtils.ts
  docs/tailwind.config.js
  docs/yarn.lock
Labels: documentation

#124 Feature: Handle auto connecting in `OpenFormatProvider`
  .changeset/clean-melons-fly.md
  docs/docs/api/react/hooks.md
  docs/docs/quickstart/react.mdx
  examples/react-next/pages/_app.tsx
  examples/react-next/pages/example.tsx
  examples/react-next/pages/index.tsx
  examples/react-next/styles.css
  sdks/react/src/provider.tsx
  sdks/react/src/wagmi-client.ts
Labels: sdk:react
